version: '3.8'
services:
  #php-apache-environment:
  #  container_name: php-apache
  #  image: php:8.0-apache
  #  volumes:
  #    - ./blog:/var/www/html/
  #  ports:
  #    - 8000:80
  #  restart: always


  testing8_0:
    build: https://raw.githubusercontent.com/Imagick/imagick/master/docker/testing8_0/Dockerfile
    volumes:
      - ./blog:/var/www/html/
    cap_add:
      - SYS_ADMIN
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    ports:
      - 8000:80
    restart: always
